### ISSUE TITLE
The program can't use SubprocVecEnv

### ISSUE THREAD

**Issue by TachikakaMin** [huangwl18/modular-rl#10] opened 2021-04-20 14:36 UTC
SubprocVecEnv uses multiprocessing which means utils.makeEnvWrapper will fail in 

def helper():
        e = gym.make("%s-v0" % env_name)
        e.seed(seed)
        return wrappers.ModularEnvWrapper(e, obs_max_len)

gym.make can't find the registered env. Because registry in gym.envs.registration will initialize again in subprocess.

**Comment by huangwl18** [comment] 2021-04-20 15:47
Some versions of gym/baselines seem to have the issue you mentioned, but the versions used in this codebase should work fine. Please make sure you're following the versions specified in [requirements.py](https://github.com/huangwl18/modular-rl/blob/master/requirements.txt) as closely as possible.

**Comment by TachikakaMin** [comment] 2021-04-21 17:06
Thanks!

Another question: https://github.com/huangwl18/modular-rl/blob/ee2487f2502d101fb96eacc8a16c5b000300db9a/src/utils.py#L64  

Are these two lines bug? 

Maybe it should be limb_obs_size = max(limb_obs_size , env.limb_obs_size) ?

**Comment by huangwl18** [comment] 2021-04-21 18:51
We assume that all the environments have the same `limb_obs_size` and `max_action`, so either should be correct.

**Comment by huangwl18** [comment] 2021-04-21 18:52
I'm closing this because it seems the issue is resolved, but feel free to email me or post in the repo if you have more questions.

**Closed by huangwl18** 2021-04-21 18:52 UTC
